[package]
name = "B-Mine-Plugin"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["dylib"]
[dependencies]
B-Mine-SDK = { path = "../B-Mine-SDK" }
# 协议库
byteorder = "1.5.0"
rust-raknet = "0.12.0"
# 日志
log = "0.4.22"
env_logger = "0.11.4"